objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <label>Pipeline</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Pipeline Connections</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Default_Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, this will be the preferred credential for Promotion deployments</inlineHelpText>
        <label>Default Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Job_Id__c</fullName>
        <description>Unique identifier used to map the result with an external job.</description>
        <externalId>true</externalId>
        <inlineHelpText>For devs to map this process with any other process that happens outside Copado.</inlineHelpText>
        <label>External Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MonitoredEnvironmentInitiator.cls
public class MonitoredEnvironmentInitiator {
    
    @testVisible
    private static List<string> testingFunctionResults;

    @InvocableMethod
    public static void FlowEntryPoint(List<string> ids)
    {
        ScanEnvironments(ids);
    }

    public static void ScanEnvironments(List<string> ids)
    {
        List<Monitored_Environments__c> monitoredEnvironments = GetMonitoredEnvironments(ids);

        List<string> validatedEnvironmentIds = ValidateEnvironmentIds(ids,monitoredEnvironments);
        
        Map<string,string> environmentMonitoredEnvironments = MapMonitoriedEnvironments(monitoredEnvironments);
        Map<string,string> environmentUserNames = GetDefaultCredentialUsernames(validatedEnvironmentIds);
        Map<string,string> environmentPipelines = GetPipelinesForEnvironments(validatedEnvironmentIds);

        Map<string,string> resultForEnvironments = new Map<string,string>();
        Map<string,Monitoring_Log__c> logs = new Map<string,Monitoring_Log__c>();
        for(string environmentId :validatedEnvironmentIds)
        {
            string integrationUserName = environmentUserNames.get(environmentId);
            string monitoredEnvironmentId = environmentMonitoredEnvironments.get(environmentId);

            List<string> results = ExecuteFunction(integrationUserName,environmentId);
            if(results.size() == 0)
            {
                throw new MonitoringException('Invoking Copado Function did not return any results for Environment: ' + environmentId + ' Integration User:' + integrationUserName);
            }

            for(string result : results)
            {
                System.debug('Result: ' + result);
            }

            string resultId = results[0];
            resultForEnvironments.put(resultId,environmentId);

            string pipelineId = environmentPipelines.get(environmentId);
            
            logs.put(environmentId,new Monitoring_Log__c(
                Environment__c = environmentId,
                Monitored_Environment__c = monitoredEnvironmentId,
                Integration_User__c = integrationUserName,
                Start_Date__c = DateTime.now(),
                Pipeline__c = pipelineId,
                Function_Result__c = resultId
            ));
        }

        insert logs.values();

        UpdateResults(logs,resultForEnvironments);

    }

    private static Map<string, string> MapMonitoriedEnvironments(List<Monitored_Environments__c> monitoredEnvironments)
    {
        Map<string, string> environmentMap = new Map<string,string>();

        for(Monitored_Environments__c environment : monitoredEnvironments)
        {
            environmentMap.put(environment.Environment__c, environment.ID);
        }

        return environmentMap;
    }

    @testVisible
    private static Map<string,string> GetDefaultCredentialUsernames(List<string> validateEnvironmentIds)
    {
        List<copado__Org__c> orgCredentials = [SELECT ID, copado__Username__c, copado__Environment__c
                                               FROM copado__Org__c 
                                               WHERE copado__Environment__c IN :validateEnvironmentIds AND copado__Default_Credential__c = true];

        Set<string> idSet = new Set<string>(validateEnvironmentIds);
        Map<string,string> environmentUsernames = new Map<string,string>();

        for(copado__Org__c credential : orgCredentials)
        {
            if(!idSet.contains(credential.copado__Environment__c) || environmentUsernames.containsKey(credential.copado__Environment__c))
            {
                continue;
            }

            idSet.remove(credential.copado__Environment__c);
            environmentUsernames.put(credential.copado__Environment__c,credential.copado__Username__c);
        }

        //Build a comma separated list and throw exception
        if(idSet.size() > 0)
        {
            throw new MonitoringException('Could not find Default Credential records with IDs: ' + CommaSeperateIds(idSet));
        }

        return environmentUsernames;
    }

    private static Map<string,string> GetPipelinesForEnvironments(List<string> validateEnvironmentIds)
    {
        //Check for both source OR destination because Production environments won't be sources.
        List<copado__Deployment_Flow_Step__c> connections = [SELECT copado__Deployment_Flow__c,copado__Source_Environment__c,copado__Destination_Environment__c
                                                             FROM   copado__Deployment_Flow_Step__c
                                                             WHERE  copado__Source_Environment__c IN :validateEnvironmentIds
                                                                OR copado__Destination_Environment__c IN :validateEnvironmentIds];


        Set<string> idSet = new Set<string>(validateEnvironmentIds);
        Map<string,string> environmentPipelines = new Map<string,string>();

        for(copado__Deployment_Flow_Step__c connection : connections)
        {
            string environmentId = '';
            if(idSet.contains(connection.copado__Source_Environment__c))
            {
                environmentId = connection.copado__Source_Environment__c;
            }

            if(idSet.contains(connection.copado__Destination_Environment__c))
            {
                environmentId = connection.copado__Destination_Environment__c;
            }

            if(environmentPipelines.containsKey(environmentId) || !idSet.contains(environmentId))
            {
                continue;
            }

            idSet.remove(environmentId);
            environmentPipelines.put(environmentId,connection.copado__Deployment_Flow__c);
        }

        //Build a comma separated list and throw exception
        if(idSet.size() > 0)
        {
            throw new MonitoringException('Could not find Pipeline records with IDs: ' + CommaSeperateIds(idSet));
        }

        return environmentPipelines;
    }

    private static void UpdateResults(Map<string,Monitoring_Log__c> logs, Map<string,string> resultForEnvironments)
    {
        List<copado__Result__c> results = [SELECT ID 
                                           FROM copado__Result__c 
                                           WHERE ID IN :resultForEnvironments.keySet() 
                                           LIMIT 1];
        
        for(copado__Result__c result : results)
        {
            string environmentId = resultForEnvironments.get(result.ID);
            Monitoring_Log__c log = logs.get(environmentId);

            result.copado__job_id__c = log.ID;
        }

        update results;
    }

    private static List<Monitored_Environments__c> GetMonitoredEnvironments(List<string> monitoredEnvironmentIds)
    {
        return [SELECT  ID, Environment__c
                FROM     Monitored_Environments__c
                WHERE    ID IN :monitoredEnvironmentIds];        
    }

    private static List<string> ValidateEnvironmentIds(List<string> ids, List<Monitored_Environments__c> monitoredEnvironments)
    {
        Set<string> idSet = new Set<string>(ids);
        List<string> environmentIds = new List<string>();

        for(Monitored_Environments__c environment : monitoredEnvironments)
        {
            if(!idSet.contains(environment.ID))
            {
                continue;
            }

            idSet.remove(environment.ID);
            environmentIds.add(environment.Environment__c);
        }

        //Build a comma separated list and throw exception
        if(idSet.size() > 0)
        {
            throw new MonitoringException('Could not find Monitored Environment records with IDs: ' + CommaSeperateIds(idSet));
        }

        return environmentIds;
    }

    private static List<string> ExecuteFunction(string integrationUserName, string environmentId)
    {
        if(Test.isRunningTest())
        {
            return testingFunctionResults;
        }

        copado.RunCopadoFunction.InvocableVariables invocableVariable = new copado.RunCopadoFunction.InvocableVariables();
        invocableVariable.functionApiName = 'setup_audit_trail';
        invocableVariable.parametersJSON = '[{"name":"IntegrationUsername","value":"' + integrationUserName + '"},{"name":"SessionID","value":"{$Context.Credential.SessionId}"},{"name":"Endpoint","value":"{$Context.Credential.Endpoint}"}]';
        invocableVariable.contextId = environmentId;

        List<copado.RunCopadoFunction.InvocableVariables> invocableVariables = new List<copado.RunCopadoFunction.InvocableVariables>{invocableVariable};
        return copado.RunCopadoFunction.execute(invocableVariables);
    }

    private static string CommaSeperateIds(Set<string> ids)
    {
        string commaSeperatedList = '';
        for(string id : ids)
        {
            if(commaSeperatedList.length() > 0)
            {
                commaSeperatedList += ', ' + id;
                continue;
            }

            commaSeperatedList = id;
        }

        return commaSeperatedList;
    }    
}