objects/copado__ExtensionConfiguration__c.object
<CustomObject>
    <description>Defines the configuration for a specific extension.</description>
    <fields>
        <fullName>copado__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__ExtensionApplication__c</fullName>
        <inlineHelpText>Select the type of Copado Application that relates to the Extension.</inlineHelpText>
        <label>Copado Phase</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__ExtensionTool__c</fullName>
        <label>Extension Tool</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Manual Tests</fullName>
                    <default>true</default>
                    <label>Manual Tests</label>
                </value>
                <value>
                    <fullName>Apex Tests</fullName>
                </value>
                <value>
                    <fullName>PMD</fullName>
                </value>
                <value>
                    <fullName>Copado Robotic Testing</fullName>
                </value>
                <value>
                    <fullName>metadata-report-hs</fullName>
                </value>
                <value>
                    <fullName>InsightAppSec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Deprecated</description>
        <label>Status - Deprecated</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Setup Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Extension Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Extension Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobExecution__c.object
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <fields>
        <fullName>copado__DataJson__c</fullName>
        <description>This field contains the test level for the Delete Metadata step.</description>
        <label>DataJson</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>It is the status of the job execution.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a reusable template with a list of steps that can be executed as part of different processes such as a commit, a promotion or a deployment.</description>
        <label>Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Job Executions</relationshipLabel>
        <relationshipName>JobExecutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobStep__c.object
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <fields>
        <fullName>copado__JobExecution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A job execution is a representation of a job template execution at a given point in time.</description>
        <label>Job Execution</label>
        <referenceTo>copado__JobExecution__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__JobTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Name of the job template which initiates the execution of the job step.</description>
        <label>Job Template</label>
        <referenceTo>copado__JobTemplate__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The latest result associated with the job step.</description>
        <label>Last Result</label>
        <referenceTo>copado__Result__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>The status of the Job Step.</description>
        <formula>IF(NOT(ISBLANK(copado__JobTemplate__c)), &apos;NA&apos;, 
  IF(copado__IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(copado__Result__c), &apos;Pending&apos;, TEXT(copado__Result__r.copado__Status__c))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <description>Type of the Job Step.</description>
        <inlineHelpText>Defines the behaviour this step will have when executed.</inlineHelpText>
        <label>Behaviour</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Function</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobTemplate__c.object
<CustomObject>
    <description>A job template is a reusable template with a list of steps that can be executed as part of different processes such as a commit, a promotion or a deployment.</description>
    <fields>
        <fullName>copado__Version__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The version of the Job Template.</description>
        <label>Version</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Error_Message__c</fullName>
        <description>Description of the error if the job has failed.</description>
        <inlineHelpText>Only displays when there&apos;s an error. It is used to inform the user about what failed during the execution of the associated process.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__JobStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
        <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this fields points to the Job Step. (note that Job Step and Function can be populated at the same time)</inlineHelpText>
        <label>Job Step</label>
        <referenceTo>copado__JobStep__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Job_Type__c</fullName>
        <description>API name of the job that triggered the result. This information can be used for reporting purposes.</description>
        <inlineHelpText>API name of the parent Job. Used for reporting purposes mainly.</inlineHelpText>
        <label>Job API Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Progress_Status__c</fullName>
        <description>This status is used to track the current job activity.</description>
        <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
        <label>Progress Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Status of the job execution.</description>
        <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Test parent object which triggered the execution.</description>
        <inlineHelpText>Test Parent object that trigger the execution.</inlineHelpText>
        <label>Test</label>
        <referenceTo>copado__Test__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Test__c.object
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <fields>
        <fullName>copado__ExtensionConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The displayed values are based on the active Extension Configuration records available in your org.</inlineHelpText>
        <label>Tool Configuration</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Make sure the selected Extension Configuration is valid and active.</errorMessage>
            <filterItems>
                <field>copado__ExtensionConfiguration__c.copado__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__ExtensionConfiguration__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>ChildTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__ReadyToRun__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>By checking this field, you are indicating that the test is ready to be executed and the &apos;Run&apos; button will display.</inlineHelpText>
        <label>Ready to Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Ready for Test</fullName>
                </value>
                <value>
                    <fullName>Testing in Progress</fullName>
                </value>
                <value>
                    <fullName>Testing Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mdreporths__UpdateTestResultFromResultTest.cls
@isTest
private with sharing class UpdateTestResultFromResultTest {
    private static final String GENERIC_TOOL_NAME = '_Generic_Test_Non-QG';
    private static final String GENERIC_TOOL_NAME_QG = '_Generic_Test_-QG';
    @isTest
    private static void executeSingleTest() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = :GENERIC_TOOL_NAME LIMIT 1];
            // Exercise 
            new UpdateTestResultFromResult().execute(null, jobStepResult, 'Success');
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = '_Generic_Test_' AND copado__Test__c != null LIMIT 1];
            System.assertEquals('Success', testResult.copado__Status__c, 'The test result should not be Failed');
        }
    }
    @isTest
    private static void executeSingleTestFailure() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = :GENERIC_TOOL_NAME LIMIT 1];
            // Exercise 
            new UpdateTestResultFromResult().execute(null, jobStepResult, 'Failed');
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = '_Generic_Test_' AND copado__Test__c != null LIMIT 1];
            System.assertEquals('Failed', testResult.copado__Status__c, 'The test result should be Failed');
        }
    }
    @isTest
    private static void executeQg() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = :GENERIC_TOOL_NAME_QG LIMIT 1];
            // Exercise 
            new UpdateTestResultFromResult().execute(null, jobStepResult, 'Success');
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = '_Generic_Test_' AND copado__Test__c = null LIMIT 1];
            System.assertEquals('Success', testResult.copado__Status__c, 'The test result should not be Failed');
        }
    }
    
    @isTest
    private static void executeQgFailure() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            copado__Result__c jobStepResult = [SELECT Id FROM copado__Result__c WHERE copado__Job_Type__c = :GENERIC_TOOL_NAME_QG LIMIT 1];
            // Exercise 
            new UpdateTestResultFromResult().execute(null, jobStepResult, 'Failed');
            // Verify
            copado__Result__c testResult = [SELECT Id, copado__Status__c, copado__Progress_Status__c, copado__Error_Message__c FROM copado__Result__c WHERE copado__Job_Type__c = '_Generic_Test_' AND copado__Test__c = null LIMIT 1];
            System.assertEquals('Failed', testResult.copado__Status__c, 'The test result should be Failed');
        }
    }
    @isTest
    private static void executeException() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            //Setup
            String errorMessage = 'Attempt to de-reference a null';
            // Exercise 
            Exception ex;
            try {
                new UpdateTestResultFromResult().execute(null, null, 'Success');
            } catch (Exception e) {
                ex = e;
            }
            // Verify
            System.assertEquals(true, ex.getMessage().contains(errorMessage), 'The exception message matches.');
        }
    }
    @TestSetup
    private static void makeData() {
        User runAsUser = new User(
            LastName = 'UserLastName',
            Username = 'username@myemail.com',
            Email = 'username@myemail.com',
            Alias = 'MyAlias',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = [SELECT Id, Name FROM Profile WHERE UserType = 'Standard' AND PermissionsPrivacyDataAccess = false AND PermissionsSubmitMacrosAllowed = true AND PermissionsMassInlineEdit = true LIMIT 1].Id,
            LanguageLocaleKey = 'en_US'
        );
        insert runAsUser;

        Set<String> permissions = new Set<String>{'Copado_User', 'Copado_Functions', 'Copado_Job_Engine', 'Configure_AQF'};
        List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
        for(PermissionSet permission : [SELECT Id, Name FROM PermissionSet WHERE Name IN :permissions]) {
            assignments.add(new PermissionSetAssignment(AssigneeId = runAsUser.Id, PermissionSetId = permission.Id));
        }
        insert assignments;

        System.runAs(runAsUser) {
            copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
            copado.GlobalAPI.UserLicense userLicense = new copado.GlobalAPI.UserLicense();
            userLicense.isCCMEnabled = true;
            userLicense.isCopadoEnabled = true;
            userLicense.userId = runAsUser.Id;
            copadoGlobalAPI.upsertCopadoLicense(userLicense);

            // default values varied according to version, and what was working in 20.0 fails in 20.5 and vice-versa
            copado__ExtensionConfiguration__c extensionConfiguration;
            try{
                extensionConfiguration = new copado__ExtensionConfiguration__c(copado__Active__c = true, copado__ExtensionTool__c = 'Manual Tests', copado__ExtensionApplication__c = 'Test');
                insert extensionConfiguration;
            }catch(Exception e) {
                extensionConfiguration = new copado__ExtensionConfiguration__c(copado__Active__c = true, copado__ExtensionTool__c = 'None', copado__ExtensionApplication__c = 'Test');
                insert extensionConfiguration;
            }
            
            copado__Test__c testItem1 = new copado__Test__c(Name = '_Generic_Test_ Test - Single Execution', copado__ExtensionConfiguration__c = extensionConfiguration.Id, copado__ReadyToRun__c = true);
            copado__Test__c testItem2 = new copado__Test__c(Name = '_Generic_Test_ Test - QG Execution', copado__ExtensionConfiguration__c = extensionConfiguration.Id, copado__ReadyToRun__c = true);
            List<copado__Test__c> tests = new List<copado__Test__c>{testItem1, testItem2};
            insert tests;
            copado__Result__c testResult = new copado__Result__c(copado__Test__c = testItem1.Id, copado__Job_Type__c = '_Generic_Test_', copado__Status__c = 'Not Started');
            copado__Result__c qGResult = new copado__Result__c(copado__Job_Type__c = '_Generic_Test_', copado__Status__c = 'Not Started');
            List<copado__Result__c> pmdTestResults = new List<copado__Result__c>{testResult, qGResult};
            insert pmdTestResults;
            copado__JobTemplate__c template = new copado__JobTemplate__c(Name = 'Run _Generic_Test_', copado__Version__c = 1);
            insert template;
            copado__JobExecution__c execution1 = new copado__JobExecution__c(
                copado__Template__c = template.Id,
                copado__DataJson__c = '{"resultIds" : [ "'+ testResult.Id +'" ]}'
            );
            copado__JobExecution__c execution2 = new copado__JobExecution__c(
                copado__Template__c = template.Id,
                copado__DataJson__c = '{"resultId" : "'+ qGResult.Id +'"}'
            );
            List<copado__JobExecution__c> executions = new List<copado__JobExecution__c>{execution1, execution2};
            insert executions;
            copado__JobStep__c jobStep1 = new copado__JobStep__c(Name = 'Evaluate _Generic_Test_ Result', copado__JobExecution__c = execution1.Id, copado__Type__c = 'Function');
            copado__JobStep__c jobStep2 = new copado__JobStep__c(Name = 'Evaluate _Generic_Test_ Result', copado__JobExecution__c = execution2.Id, copado__Type__c = 'Function');
            List<copado__JobStep__c> jobSteps = new List<copado__JobStep__c>{jobStep1, jobStep2};
            insert jobSteps;
            copado__Result__c jobStepResult1 = new copado__Result__c(copado__Job_Type__c = GENERIC_TOOL_NAME, copado__JobStep__c = jobStep1.Id, copado__Status__c = 'Success');
            copado__Result__c jobStepResult2 = new copado__Result__c(copado__Job_Type__c = GENERIC_TOOL_NAME_QG, copado__JobStep__c = jobStep2.Id, copado__Status__c = 'Success');
            List<copado__Result__c> results = new List<copado__Result__c>{jobStepResult1, jobStepResult2};
            insert results;
        }
    }
}