objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Credential</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>copado__Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Deployments (From Credential)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <formula>IF(NOT(ISBLANK(copado__Promotion__r.copado__Project__c)), copado__Promotion__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c,  copado__Promotion__r.copado__Release__r.copado__Project__r.copado__Deployment_Flow__r.copado__Git_Repository__c )</formula>
        <label>Git Repository</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <formula>copado__From_Org__r.copado__Environment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source Environment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
                <value>
                    <fullName>Merge Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>copado__Enable_Copado_DX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Copado DX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Main_Branch__c</fullName>
        <description>Main branch of the selected Git Repository (e.g. master).</description>
        <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <label>Pipeline</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Pipeline Connections</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>copado__Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Org ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <fields>
        <fullName>copado__Branch_Base_URL__c</fullName>
        <description>This field enables Copado to create a link to the Git branches&apos; information on your provider&apos;s end.</description>
        <inlineHelpText>Base URL of your Repository branches, e.g.: https://github.com/[COMPANY]/[REPOSITORY]/tree/</inlineHelpText>
        <label>Branch Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Git_Provider__c</fullName>
        <description>Copado generates specific links to the Git Repository, its branches and commits based on the selected Git Provider.</description>
        <inlineHelpText>Copado generates specific links to the Git Repository, its branches and commits based on the selected Git Provider.</inlineHelpText>
        <label>Git Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Github</fullName>
                </value>
                <value>
                    <fullName>Bitbucket</fullName>
                </value>
                <value>
                    <fullName>GitLab</fullName>
                </value>
                <value>
                    <fullName>Microsoft Team Service</fullName>
                </value>
                <value>
                    <fullName>Copado Version Control</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Source_Format__c</fullName>
        <description>Choose between standard Metadata API folder and file structure or DX source structure that uses a different set of files and file extensions. Default is Metadata.</description>
        <inlineHelpText>Choose between standard Metadata API folder and file structure or DX source structure that uses a different set of files and file extensions. Default is Metadata.</inlineHelpText>
        <label>Source Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Metadata</fullName>
                    <default>true</default>
                    <label>Metadata</label>
                </value>
                <value>
                    <fullName>DX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Default_Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, this will be the preferred credential for Promotion deployments</inlineHelpText>
        <label>Default Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the deployment that triggered the result.</description>
        <inlineHelpText>Deployment Parent object that trigger the execution. (for legacy)</inlineHelpText>
        <label>Deployment</label>
        <referenceTo>copado__Deployment__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Job_Id__c</fullName>
        <description>Unique identifier used to map the result with an external job.</description>
        <externalId>true</externalId>
        <inlineHelpText>For devs to map this process with any other process that happens outside Copado.</inlineHelpText>
        <label>External Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Job_Type__c</fullName>
        <description>API name of the job that triggered the result. This information can be used for reporting purposes.</description>
        <inlineHelpText>API name of the parent Job. Used for reporting purposes mainly.</inlineHelpText>
        <label>Job API Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Status of the job execution.</description>
        <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MonitoredEnvironmentInitiatorTests.cls
@isTest
public class MonitoredEnvironmentInitiatorTests {
    @TestSetup
    private static void createData() {
        MonitorTestHelper.setup();
    }
    @isTest
    public static void GetDefaultCredentialsForEnvironment()
    {
        Boolean exceptionThrown = false;
        List<string> ids = new List<string>();

        string missingCredentialId = 'MissingCredentialID';
        try {
            exceptionThrown = false;

            ids.clear();
            ids.add(missingCredentialId);

            MonitoredEnvironmentInitiator.GetDefaultCredentialUsernames(ids);

        } catch (MonitoringException e) {
            exceptionThrown = true;
            System.assertEquals('Could not find Default Credential records with IDs: ' + missingCredentialId, e.getMessage());
        }

        System.assertEquals(true, exceptionThrown);

        //Valid Use case of one 
        copado__Environment__c environment;
        try {
            exceptionThrown = false;

            environment = new copado__Environment__c(
                Name = 'Test environment 1',
                copado__Type__c = 'Sandbox',
                copado__Org_ID__c = '123456789012345678'
            );

            insert environment;

            copado__Org__c org = new copado__Org__c(
                copado__Environment__c = environment.ID,
                copado__Default_Credential__c = true,
                copado__Org_Type__c = 'Sandbox',
                copado__Username__c = ''
            );

            insert org;

            ids.clear();
            ids.add(environment.Id);

            MonitoredEnvironmentInitiator.GetDefaultCredentialUsernames(ids);
        } catch (MonitoringException e) {
            exceptionThrown = true;
        }

        System.assertEquals(false, exceptionThrown);
    }

    @isTest
    public static void FlowEntryPoint()
    {
        System.runAs(MonitorTestHelper.getRunAsUser()){
            copado__Git_Repository__c repo = new copado__Git_Repository__c(
                copado__Git_Provider__c = 'Github',
                copado__Branch_Base_URL__c = 'main',
                copado__Source_Format__c = 'Metadata'
            );

            insert repo;

            copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(
                copado__Git_Repository__c = repo.id,
                COPADO__ENABLE_COPADO_DX__C = false,
                COPADO__MAIN_BRANCH__C = 'main'
            );

            insert pipeline;

            copado__Environment__c environment = new copado__Environment__c(
                    Name = 'Test environment 1',
                    copado__Type__c = 'Sandbox',
                    copado__Org_ID__c = '123456789012345678'
                );
            insert environment;

            copado__Deployment_Flow_Step__c deploymentStep = new copado__Deployment_Flow_Step__c(
                copado__Source_Environment__c = environment.ID,
                copado__Deployment_Flow__c = pipeline.ID
            );
            insert deploymentStep;

            Monitored_Environments__c monitoredEnvironment = new Monitored_Environments__c(
                    Environment__c = environment.ID,
                    Pipeline__c = pipeline.ID
                );
            insert monitoredEnvironment;

            copado__Org__c org = new copado__Org__c(
                    copado__Environment__c = environment.ID,
                    copado__Default_Credential__c = true,
                    copado__Org_Type__c = 'Sandbox',
                    copado__Username__c = 'Default Org Credential Username'
                );
            insert org;

            copado__Deployment__c deployment = new copado__Deployment__c(
                copado__From_Org__c = org.ID
            );
            insert deployment;

            copado__Destination_Org__c destinationOrg = new copado__Destination_Org__c(
                copado__Deployment__c = deployment.ID,
                copado__To_Org__c = org.ID
            );
            insert destinationOrg;

            copado__Step__c step = new Copado__Step__c(
                    copado__Deployment__c = deployment.ID
                );
            insert step;

            copado__Deployment_Job__c deploymentJob = new copado__Deployment_Job__c(
                copado__status__c = 'Success',
                copado__Step__c = step.ID,
                copado__Destination_Org__c = destinationOrg.ID
            );
            insert deploymentJob;

            copado__Result__c result = new copado__Result__c(
                    copado__job_id__c = null,
                    copado__Job_Type__c = 'Unit Test'
            );
            insert result;

            MonitoredEnvironmentInitiator.testingFunctionResults = new List<string> { result.ID };

            Test.startTest();

            MonitoredEnvironmentInitiator.FlowEntryPoint(new List<string> { monitoredEnvironment.ID });

            Test.stopTest();

            result = [SELECT ID,copado__job_id__c
                    FROM copado__Result__c 
                    WHERE ID = :result.ID 
                    LIMIT 1];

            System.assert(result.copado__job_id__c != null,'Verify that the Log ID is saved to the Result object');
        }
    }
}