objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Test parent object which triggered the execution.</description>
        <inlineHelpText>Test Parent object that trigger the execution.</inlineHelpText>
        <label>Test</label>
        <referenceTo>copado__Test__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Test__c.object
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mdreporths__TestResultViewerReadFile.cls
public with sharing class TestResultViewerReadFile {
    @testVisible
    private final static String documentTitle = 'metadata_report_hs.json';

    // NOTE: objectId can be a Test or a Test Result?
    @AuraEnabled(cacheable=true)
    public static Response readFile(Id objectId) {
        String parentId = objectId;
        Schema.SObjectType token = objectId.getSObjectType();
        if( token == copado__Result__c.sObjectType ) {
            // no need to do anything(?)
        }else if( token == copado__Test__c.sObjectType ) {
            // TODO: find the ... last result associated with this?
            copado__Result__c[] results = [SELECT Id FROM copado__Result__c WHERE copado__Test__c = :parentId WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC LIMIT 1];
            if(!results.isempty()) {
                parentId = results[0].Id;
            }
        }

        System.debug('request: '+objectId+' '+parentId+' '+documentTitle);
        Response response = new Response();

        List<ContentDocumentLink> cdls = [SELECT 
            ContentDocumentId,
            ContentDocument.LatestPublishedVersion.ContentSize, 
            ContentDocument.LatestPublishedVersion.VersionData
                FROM ContentDocumentLink 
                WHERE LinkedEntityId = :parentId 
                AND (ContentDocument.Title = :documentTitle OR ContentDocument.Title = :documentTitle.substringBeforeLast('.') )
                WITH SECURITY_ENFORCED ORDER BY ContentDocument.LastModifiedDate DESC LIMIT 1];
        for(ContentDocumentLink cdl : cdls) {
            response.contentDocumentId = cdl.ContentDocumentId;
            response.size = cdl.ContentDocument.LatestPublishedVersion.ContentSize;
            if(response.size < 5000000) {
                response.data = cdl.ContentDocument.LatestPublishedVersion.VersionData.toString();
            }
        }

        return response;
    }

    public with sharing class Response {
        @AuraEnabled
        public Integer size=0;
        @AuraEnabled
        public String data;
        @AuraEnabled
        public String contentDocumentId;
    }

    public with sharing class CustomException extends Exception {}
}