objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Job_Type__c</fullName>
        <description>API name of the job that triggered the result. This information can be used for reporting purposes.</description>
        <inlineHelpText>API name of the parent Job. Used for reporting purposes mainly.</inlineHelpText>
        <label>Job API Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Test parent object which triggered the execution.</description>
        <inlineHelpText>Test Parent object that trigger the execution.</inlineHelpText>
        <label>Test</label>
        <referenceTo>copado__Test__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Test__c.object
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mdreporths__TestResultViewerReadFileTest.cls
@isTest
private with sharing class TestResultViewerReadFileTest {
    @isTest
    private static void testSuccess() {
        copado__Test__c test = new copado__Test__c();
        insert test;
        copado__Result__c result = new copado__Result__c(copado__Test__c=test.Id, copado__Job_Type__c='Integration');
        insert result;

        // create the mock file
        ContentVersion cv = new ContentVersion();
        cv.PathOnClient = TestResultViewerReadFile.documentTitle;
        cv.Title = TestResultViewerReadFile.documentTitle;
        cv.VersionData = Blob.valueOf('test file body');
        insert cv;
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.LinkedEntityId = result.Id;
        cdl.ShareType = 'V';
        insert cdl;

        TestResultViewerReadFile.Response resp = TestResultViewerReadFile.readFile(test.Id);
        System.assert(resp.size>0, 'File should be found');
    }

}