objects/copado__Function__c.object
<CustomObject>
    <description>A function is a script that contains a series of commands and can be executed from Copado.</description>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobExecution__c.object
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__JobStep__c.object
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <fields>
        <fullName>copado__JobExecution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A job execution is a representation of a job template execution at a given point in time.</description>
        <label>Job Execution</label>
        <referenceTo>copado__JobExecution__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The latest result associated with the job step.</description>
        <label>Last Result</label>
        <referenceTo>copado__Result__c</referenceTo>
        <relationshipLabel>Job Steps</relationshipLabel>
        <relationshipName>JobSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>The status of the Job Step.</description>
        <formula>IF(NOT(ISBLANK(copado__JobTemplate__c)), &apos;NA&apos;, 
  IF(copado__IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(copado__Result__c), &apos;Pending&apos;, TEXT(copado__Result__r.copado__Status__c))))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Error_Message__c</fullName>
        <description>Description of the error if the job has failed.</description>
        <inlineHelpText>Only displays when there&apos;s an error. It is used to inform the user about what failed during the execution of the associated process.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__Function__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the function that triggered the result.</description>
        <inlineHelpText>Function Parent object that trigger the execution.</inlineHelpText>
        <label>Function</label>
        <referenceTo>copado__Function__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__JobStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
        <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this fields points to the Job Step. (note that Job Step and Function can be populated at the same time)</inlineHelpText>
        <label>Job Step</label>
        <referenceTo>copado__JobStep__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Progress_Status__c</fullName>
        <description>This status is used to track the current job activity.</description>
        <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
        <label>Progress Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <defaultValue>&quot;Not Started&quot;</defaultValue>
        <description>Status of the job execution.</description>
        <inlineHelpText>Current status of the result. Confirms if the result is pending or completed.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mdreporths__UpdateTestResultFromResult.cls
/*
 * Necessary workaround when running a Test tool as a Test, not as a Quality Gate
 */
global with sharing class UpdateTestResultFromResult implements copado.MCCallback {

    // Entrypoint of a Flow Action to update test results
    @InvocableMethod(label='Update Test Result From Result' category='Copado')
    public static void execute(List<Request> requests) {
        for(Request request : requests) {
            // NOTE: this is not bulkified, but since it is a temporary workaround, it should not matter
            updateTestResult(request.resultId, request.status, request.resultData, request.errorMessage);
        }
    }

    // Entrypoint of a Function callback
    global void execute(copado__Function__c function, copado__Result__c result, String status) {
        updateTestResult(result.Id, status, null, null);
    }

    @SuppressWarnings('PMD.ExcessiveParameterList')
    global static void updateTestResult(Id resultId, String status, String resultData, String errorMessage) {
        String jobExecutionPayload = [SELECT copado__JobStep__r.copado__JobExecution__r.copado__DataJson__c 
                                      FROM copado__Result__c 
                                      WHERE Id= :resultId WITH SECURITY_ENFORCED LIMIT 1
                                      ][0].copado__JobStep__r.copado__JobExecution__r.copado__DataJson__c;
        Map<String,Object> jobPayload = (Map<String,Object>) System.JSON.deserializeUntyped(jobExecutionPayload);
        Set<Id> resultIds = new Set<Id>();
        if(jobPayload.get('resultId')!=null) {
            // Consolidated result is not null
            resultIds.add( (String)jobPayload.get('resultId') );
        } else if(jobPayload.get('resultIds')!=null) {
            // Consolidated result is null but there are individual results
            for(Object rid : (List<Object>)jobPayload.get('resultIds')) {
                resultIds.add( (String)rid );
            }
        }
        System.debug('looking for resultIds='+resultIds);
        List<copado__Result__c> results = [SELECT copado__Status__c, copado__Progress_Status__c
            FROM copado__Result__c WHERE Id IN :resultIds WITH SECURITY_ENFORCED];
        for(copado__Result__c result : results) {
            String finalStatus = status == 'Success' ? 'Success' : 'Failed';
            result.copado__Status__c = finalStatus;
            result.copado__Progress_Status__c = errorMessage;
            result.copado__Error_Message__c = errorMessage;
        }
        System.debug('updating results='+results);
        if(Schema.sObjectType.copado__Result__c.isUpdateable()) {
            update results;
        }
    }

    global with sharing class CustomException extends Exception {}

    global with sharing class Request {
        @InvocableVariable
        public Id resultId;
        @InvocableVariable
        public String status;
        @InvocableVariable
        public String resultData;
        @InvocableVariable
        public String errorMessage;
    }
}